### ISSUE TITLE
Support Thinkpad T420 with Coreboot two fingures scorlling in Windows

### ISSUE THREAD

**Issue by corechip** [coolstar/crostrackpad3#7]
I have a thinkpad t420 with coreboot + seabios. The Synaptics touchpad 2 fingures scorlling works in linux but not windows. The official synaptics can not find the device. I tried this crostrackpad, but it can not find the device. Is it possible to support this?

**Comment by corechip** [comment]
I can provide some debug log if you want.

**Comment by coolstar** [comment]
This driver only supports the i2c trackpads on the chromebooks. For your Thinkpad T420, you want to use the official Synaptics driver. The issue in coreboot is due to the incorrect _HID in coreboot's DSDT. Update the DSDT with the proper Synaptics Hardware ID from the vendor firmware and the official Synaptics driver will work.
